export const bstPseudo = [
  'class Node:',
  '  value = given value',
  '  left = null',
  '  right = null',
  '',
  'class BST:',
  '  root = null',
  '',
  '  function insert(value):',
  '    if root is null:',
  '      root = new Node(value)',
  '    else:',
  '      insertHelper(root, value)',
  '',
  '  function insertHelper(node, value):',
  '    if value < node.value:',
  '      if node.left is null:',
  '        node.left = new Node(value)',
  '      else:',
  '        insertHelper(node.left, value)',
  '    else:',
  '      if node.right is null:',
  '        node.right = new Node(value)',
  '      else:',
  '        insertHelper(node.right, value)',
]