export const mergeSortPseudo = [
  'function mergeSort(arr):',
  '  if length of arr <= 1:',
  '    return arr',
  '  mid = length of arr / 2',
  '  left = mergeSort(arr[0 to mid])',
  '  right = mergeSort(arr[mid to end])',
  '  return merge(left, right)',
  '',
  'function merge(left, right):',
  '  result = []',
  '  while left and right are not empty:',
  '    if left[0] <= right[0]:',
  '      append left[0] to result',
  '      remove left[0] from left',
  '    else:',
  '      append right[0] to result',
  '      remove right[0] from right',
  '  append remaining elements to result',
  '  return result',
]