// graphPseudocode.ts

export const graphPseudocode: Record<string, string[]> = {
  BFS: [
    'function BFS(graph, start):',
    '  create empty queue Q',
    '  create empty set visited',
    '  add start to Q',
    '  add start to visited',
    '  while Q is not empty:',
    '    node = Q.dequeue()',
    '    process(node)',
    '    for each neighbour in graph.neighbours(node):',
    '      if neighbour not in visited:',
    '        add neighbour to visited',
    '        Q.enqueue(neighbour)',
  ],

  DFS: [
    'function DFS(graph, start):',
    '  create empty stack S',
    '  create empty set visited',
    '  push start onto S',
    '  while S is not empty:',
    '    node = S.pop()',
    '    if node not in visited:',
    '      add node to visited',
    '      process(node)',
    '      for each neighbour in graph.neighbours(node):',
    '        if neighbour not in visited:',
    '          S.push(neighbour)',
  ],

  Dijkstra: [
    'function Dijkstra(graph, start, end):',
    '  dist = map of node to infinity',
    '  dist[start] = 0',
    '  create priority queue PQ, add start with dist 0',
    '  while PQ is not empty:',
    '    node = PQ.pop_lowest_dist()',
    '    if node already visited: continue',
    '    mark node as visited',
    '    if node == end: return path',
    '    for each neighbour of node:',
    '      new_dist = dist[node] + weight(node, neighbour)',
    '      if new_dist < dist[neighbour]:',
    '        dist[neighbour] = new_dist',
    '        parent[neighbour] = node',
    '        PQ.add(neighbour, new_dist)',
  ],
  'A*': [
    'function A*(graph, start, end):',
    '  g = map of node to infinity',
    '  f = map of node to infinity',
    '  g[start] = 0',
    '  f[start] = heuristic(start, end)',
    '  create open set, add start',
    '  while open set is not empty:',
    '    node = open.pop_lowest_f()',
    '    if node == end: return path',
    '    for each neighbour of node:',
    '      new_g = g[node] + weight(node, n)',
    '      if new_g < g[neighbour]:',
    '        g[neighbour] = new_g',
    '        f[neighbour] = new_g + heuristic(n, end)',
    '        parent[neighbour] = node',
    '        if neighbour not in open: open.add(neighbour)',
  ],
}